### ISSUE TITLE
The final results on camera_shadow dataset

### ISSUE THREAD

**Issue by m-richa** [Mumeishi514/d_2nerf#11]
After training for 100000 steps, the static part still has hand shadows. Does it need to be trained more?

**Comment by ChikaYan** [comment]
Hi, usually the separation becomes fixed at quite early iterations, so 100k is definitely enough. May I ask what configuration did you use to train the model? Also please note that due to the strong view dependency of camera/hand in this dataset, it's sometimes quite difficult for the model to perfectly tell whether the shadow is a view-dependent effect or dynamic effect without any additional priors. Hence it is expected to have some artifacts in the separation.

Hope that helps!
