### ISSUE TITLE
Adaptivity to other dynamic datasets

### ISSUE THREAD

**Issue by ntaquan0125** [Mumeishi514/d_2nerf#20]
Dear authors,

Thank you for your excellent work.

I have tested the method on several outdoor scenes involving high ego-motion; however, the results are not entirely satisfactory. Do you believe there might be a gap in adapting to this type of data, or are there adjustments I could make to achieve better separation in such scenarios?

I also played with the hyperparameters but this is the best I can get.

![d2nerf_kitti](https://github.com/ChikaYan/d2nerf/assets/54766660/025cb60c-9e04-4d9c-b8c3-c05001d39b8d)

**Comment by ChikaYan** [comment]
Hi,

Thx for your interest in our work. Decoupling of outdoor scenes might be quite challenging due to global brightness changes. You might be able to get better results by tweaking the skewness hyperparameters, but know that this is a relatively old work and you might want to try some newer methods such as https://omnimatte-rf.github.io/ first to see if it gives better results.

Best
